### ISSUE TITLE
Cache gorm

### ISSUE THREAD

**Issue by pjebs** [benguild/GAEBridge#4]
Here is my solution for caching gorm on GAE.
It can be used for anything - not just database queries.

https://github.com/pjebs/GAE-Toolkit-Go

**Comment by benguild** [comment]
So, I ended up writing a fairly sophisticated `cache` helper on my own in the end.

**The reasons being that:**
1. There's risk of the cache being stale if there's an error writing to it, which can create real issues if you're caching any data that's ever updated. So, you need to make sure your code/behavior is consistent throughout the entire application.
2. If you're fetching a lot of individual records, you need to batch fetch/write instead... or there's at least 1-2ms of latency per fetch/write. Given this limitation, you might as well write a cache layer and have your code be centralized for it even if you're only fetching a single record in certain cases. _— Tip: The `appengine.memcache` helper actually uses its own batch method internally through its simpler single record fetch interface as well, so that's pretty much the expected behavior anyway I guess._
3. A few other things that I can't think of off the top of my head right now... but caching can be somewhat complicated so there's a lot to it.

I've considered releasing some of this code that I wrote, but probably not in this `GAEBridge` package since it's not specific to App Engine and this package is only sort of patching/bridging any critical gaps or differences in that implementation. Since the only one I ended up really running into was with the logging (as we solved a while back) ... I think we're good for now? :)

**Comment by pjebs** [comment]
I don't understand what is wrong with my code regarding above?

**Comment by benguild** [comment]
At the most basic level, your implementation abstracts away the ability to batch get/set requests to fetch or store many items in the cache at once. There's 1-2ms of latency on each request, so if you need to fetch 500 items quickly, it could take ~500-1000ms for that request with your implementation to get all of the records, instead of much less....

**Comment by pjebs** [comment]
Ben, did you get the email I sent regarding the database/sql ebook?

**Comment by benguild** [comment]
Hey sorry, your emails are going into spam on Gmail. I found it and I'll check it out.

**Comment by pjebs** [comment]
I thought the error handling was a revelation.
For example, if I wanted to detect a particular type of error I respond differently I would do something like this:

```
//Check if already purchased
        if strings.Contains(err.Error(), "Error 1062") && strings.Contains(err.Error(), "'customer_event_customer_id_event_id_unique'") { //"Error 1062: Duplicate entry '1-1' for key 'customer_event_customer_id_event_id_unique'"
            e.ReturnError(w, e.CustomerAlreadyPurchasedEvent, err.Error())
            return
        }

        //Check if event exists
        if strings.Contains(err.Error(), "Error 1452") && strings.Contains(err.Error(), "`customer_event_event_id_foreign`") { //"Error 1452: Cannot add or update a child row: a foreign key constraint fails (`customer_event`, CONSTRAINT `customer_event_event_id_foreign` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`))",
            e.ReturnError(w, e.EventNotFound, err.Error())
            return
        }
```

**Comment by pjebs** [comment]
The mysql error messages are in fact customized based on language and some other factors. I don't think it mattered for me though because I was looking for the violating key and error code only and I'm sure they won't change based on language.

I noticed in the book that there is a fool-proof way: the driver actually provides a custom error type you can type assert to which will reveal the code etc as fields in the error type.

**Comment by benguild** [comment]
Oh yeah you should never do string comparison like that. Always check the error code as an integer. Why would you check for a string match? 😄

**Comment by pjebs** [comment]
Well i didn't know there was any other information to get more details of what the error was.

**Comment by benguild** [comment]
Yikes. I do this in my database helper to make sure there's only one instance of the 1062 constant in the code:

``` go
func IsErrorDuplicateEntrySQLError(err error) (bool) {
    if mysqlError, ok := err.(*mysql.MySQLError); ok && mysqlError.Number==1062 {
        return true;

    }

    return false;

}
```

You should probably do something like that for each error you want to check out.

**Comment by pjebs** [comment]
That's what I learnt from the book. I had no idea that the mysql driver has a nice custom error type.

**Comment by pjebs** [comment]
Just be wary that Gorm has it's own error type that is actually a slice of potentially multiple errors and you may have to iterate over the slice.

**Comment by benguild** [comment]
Yeah... it's the same for the `appengine` package when dealing with Memcache batch fetching/setting: https://cloud.google.com/appengine/docs/go/reference#MultiError
